#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Complex
  include ::Thrift::Struct, ::Thrift::Struct_Union
  REAL = 1
  IMAGINARY = 2

  FIELDS = {
    REAL => {:type => ::Thrift::Types::I64, :name => 'real'},
    IMAGINARY => {:type => ::Thrift::Types::I64, :name => 'imaginary'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class ZeroDivisionException < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union

  FIELDS = {

  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

